### ISSUE TITLE
Add a gh-page branch for a styled, filterable list

### ISSUE THREAD

**Issue by brittanystoroz** [RichardLitt/awesome-conferences#26]
Let's mebe have a gh-page branch to host an index page where we can highlight upcoming conferences, open CFPs, open registrations and filter by language/location/date/what have you.

**Comment by simonv3** [comment]
What if you wrote a rake script that parsed the list in the readme and regularly extracted it to a dataset that you then use in a gh-pages structure?

It could be extracted to I really like how http://opendiversitydata.org/ is organized (https://github.com/doubleunion/opendiversitydata).

**Comment by RichardLitt** [comment]
That would work! Got a rake script we could use? Maybe modeled off of that one I gave you a while ago? ;)

**Comment by simonv3** [comment]
Wouldn't really be the same thing, but I can probably come up with something. What kind of data model do you have in mind?

**Comment by RichardLitt** [comment]
I don't have one at the moment - I keep meaning to find time to do this project, and I consistently fail to do so. Not enough spoons.

**Comment by simonv3** [comment]
This isn't complete then? https://github.com/RichardLitt/awesome-conferences/blob/master/PLANS.md

**Comment by Stephn-R** [comment]
@brittanystoroz @simonv3 @RichardLitt Hey all, checkout the gh-pages branch. Its a WIP but I am building one out.

**Comment by RichardLitt** [comment]
@simonv3 Oh man totally forgot about that. That looks good to me. @Stephn-R Awesome!

**Comment by simonv3** [comment]
@Stephn-R Cool! Do you have any visuals or plans for the site that I could have a look at?

**Comment by Stephn-R** [comment]
@simonv3 no plans just yet. I was setting the groundwork so far. I am open to ideas but the plan is to use AngularJS and Material Design Lite thus far.

**Comment by simonv3** [comment]
@Stephn-R Sounds good to me.

I was thinking structure wise it might make sense to also add tags to each entry "has-code-of-conduct", "has-diverse-speakers", "offers-stipends", "pays-airfare", etc that could be used and translated to icons. Real quick mockup: 

![screenshot 2015-07-15 09 36 24](https://cloud.githubusercontent.com/assets/485583/8705269/07bc69b4-2ad5-11e5-9443-a3094f1b744f.png)

I think the tags make sense because it means we don't really have to limit ourselves data-structure wise. Tags could be structured like 

```
{
'slug': <slug>,
'name': <name>,
'link': <link-to-relevant-thing>
}
```
Where link is a link to the conferences relevant policy description (if there is one).

**Comment by RichardLitt** [comment]
We can do this in the future. For now, I think we need to overhaul the information we actually have in this list. Closing this as stale.
